"""baseline schema

Revision ID: c18c6c73309d
Revises: 
Create Date: 2026-06-18 15:52:28.389179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c18c6c73309d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_main_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ledger_root', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('write_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('single_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month_file_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lookahead_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payee', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('narration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override_amounts', sa.JSON(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=True),
    sa.Column('override_narration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('written_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sprout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'due_date')
    )
    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrence_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrence_schedule_id'))

    op.drop_table('occurrence')
    op.drop_table('schedule')
    op.drop_table('appconfig')
    # ### end Alembic commands ###
